version: '3.8'
services:
  vue-frontend:
    build: ./epub-reader-frontend
    volumes:
      - ./epub-reader-frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development


  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
       - database

  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - books_db:/data/db

volumes:
  books_db:
