version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    depends_on:
       - database

  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - books_db:/data/db

volumes:
  books_db:
